name: Check
on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  install-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    needs: install-node-modules
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm clean
          pnpm install
          pnpm build
          pnpm build-pack

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: |
            packages/**/build
            packages/**/dist

  lint:
    runs-on: ubuntu-latest
    needs: install-node-modules
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm build-lint-deps
          pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [install-node-modules, build]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-artifacts
          path: packages

      - uses: actions/cache/restore@v5
        id: vitest-module-cache-restore
        with:
          path: "node_modules/.experimental-vitest-cache"
          key: ${{ runner.os }}-vitest-module-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Test
        run: |
          CI=1 pnpm test run

      - name: Delete Previous Cache
        if: ${{ steps.vitest-module-cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ steps.vitest-module-cache-restore.outputs.cache-primary-key }}" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache/save@v5
        id: vitest-module-cache-save
        if: always()
        with:
          path: "node_modules/.experimental-vitest-cache"
          key: ${{ steps.vitest-module-cache-restore.outputs.cache-primary-key }}
