name: Check
on:
  pull_request:
  workflow_call:

jobs:
  install-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          corepack enable

      - uses: actions/cache@v5
        with:
          path: ".yarn/cache"
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn install --immutable

  build:
    runs-on: ubuntu-latest
    needs: install-node-modules
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          corepack enable

      - uses: actions/cache@v5
        with:
          path: ".yarn/cache"
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn install --immutable

      - name: Build
        run: |
          yarn clean
          yarn build
          yarn build-pack

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: |
            packages/**/build
            packages/**/dist

  lint:
    runs-on: ubuntu-latest
    needs: install-node-modules
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
    
      - name: Install node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          corepack enable

      - uses: actions/cache@v5
        with:
          path: ".yarn/cache"
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn install --immutable

      - name: Lint
        run: |
          yarn build-lint-deps
          yarn lint

  test:
    runs-on: ubuntu-latest
    needs: [install-node-modules, build]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
    
      - name: Install node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install
          corepack enable

      - uses: actions/cache@v5
        with:
          path: ".yarn/cache"
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn install --immutable

      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-artifacts
          path: packages

      - uses: actions/cache/restore@v5
        id: vitest-module-cache-restore
        with:
          path: "node_modules/.experimental-vitest-cache"
          key: ${{ runner.os }}-vitest-module-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Test
        run: |
          CI=1 yarn test run

      - name: Delete Previous Cache
        if: ${{ steps.vitest-module-cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ steps.vitest-module-cache-restore.outputs.cache-primary-key }}" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache/save@v5
        id: vitest-module-cache-save
        if: always()
        with:
          path: "node_modules/.experimental-vitest-cache"
          key: ${{ steps.vitest-module-cache-restore.outputs.cache-primary-key }}
