name: Publish
on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: yarn
      - name: Install
        run: |
          npm install -g yarn
          yarn
      - name: Lint
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build-pack
      - name: Test
        run: |
          yarn test
      - name: Changeset
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.cjs
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
