name: Publish
on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 22.5.0
          nvm use 22.5.0
          corepack enable

      - uses: actions/cache@v4
        with:
          path: ".yarn/cache"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn install --immutable

      - name: Lint
        run: |
          yarn build-lint-deps
          yarn lint

      - name: Build
        run: |
          yarn workspace @fncts/transformers build && yarn workspace @fncts/transformers build-cjs
          yarn build-pack

      - name: Test
        run: |
          yarn test

      - name: Changeset
        id: changesets
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.cjs
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
